Repository UMC-TOMORROW/Tomorrow-Backend, pull requests merged in 2025-08, with the labels that each got.

#107 Fix: 커리어톡 게시글 여부인지 판단 로직 추가
  src/main/java/com/umc/tomorrow/domain/careertalk/controller/CareertalkController.java
  src/main/java/com/umc/tomorrow/domain/careertalk/dto/response/GetCareertalkResponseDto.java
  src/main/java/com/umc/tomorrow/domain/careertalk/service/query/CareertalkQueryService.java
  src/main/java/com/umc/tomorrow/domain/careertalk/service/query/CareertalkQueryServiceImpl.java
Labels: enhancement

#113 Fix : 이력서 저장 부분 수정
  src/main/java/com/umc/tomorrow/domain/resume/certificate/entity/Certificate.java
  src/main/java/com/umc/tomorrow/domain/resume/converter/ResumeConverter.java
  src/main/java/com/umc/tomorrow/domain/resume/dto/request/ResumeSaveRequestDTO.java
Labels: bug

#118 Fix: 자격증 관련 로직 수정
  src/main/java/com/umc/tomorrow/domain/application/converter/ApplicationConverter.java
  src/main/java/com/umc/tomorrow/domain/certificate/controller/CertificateController.java
  src/main/java/com/umc/tomorrow/domain/certificate/dto/response/CertificateResponse.java
  src/main/java/com/umc/tomorrow/domain/certificate/entity/Certificate.java
  src/main/java/com/umc/tomorrow/domain/certificate/exception/CertificateException.java
  src/main/java/com/umc/tomorrow/domain/certificate/exception/code/CertificateErrorStatus.java
  src/main/java/com/umc/tomorrow/domain/certificate/repository/CertificateRepository.java
  src/main/java/com/umc/tomorrow/domain/certificate/service/command/CertificateCommandService.java
  src/main/java/com/umc/tomorrow/domain/certificate/service/command/CertificateCommandServiceImpl.java
  src/main/java/com/umc/tomorrow/domain/resume/certificate/service/command/CertificateCommandService.java
  src/main/java/com/umc/tomorrow/domain/resume/converter/ResumeConverter.java
  src/main/java/com/umc/tomorrow/domain/resume/entity/Resume.java
  src/main/java/com/umc/tomorrow/domain/resume/exception/code/ResumeErrorStatus.java
Labels: bug

#121 Fix: 커리어톡 값 유효성 검증 로직 수정
  src/main/java/com/umc/tomorrow/domain/careertalk/controller/CareertalkController.java
  src/main/java/com/umc/tomorrow/domain/temp/PingController.java
  src/main/java/com/umc/tomorrow/global/common/exception/ExceptionAdvice.java
Labels: bug

#122 Feat: 자격증 조회
  src/main/java/com/umc/tomorrow/domain/certificate/controller/CertificateController.java
  src/main/java/com/umc/tomorrow/domain/certificate/repository/CertificateRepository.java
  src/main/java/com/umc/tomorrow/domain/certificate/service/query/CertificateQueryService.java
  src/main/java/com/umc/tomorrow/domain/certificate/service/query/CertificateQueryServiceImpl.java
Labels: enhancement

#129 feat: 찜(JobBookmark) 기능 구현
  src/main/java/com/umc/tomorrow/domain/job/entity/Job.java
  src/main/java/com/umc/tomorrow/domain/jobbookmark/controller/JobBookmarkController.java
  src/main/java/com/umc/tomorrow/domain/jobbookmark/converter/JobBookmarkConverter.java
  src/main/java/com/umc/tomorrow/domain/jobbookmark/dto/response/GetJobBookmarkListResponseDTO.java
  src/main/java/com/umc/tomorrow/domain/jobbookmark/dto/response/JobBookmarkResponseDTO.java
  src/main/java/com/umc/tomorrow/domain/jobbookmark/entity/JobBookmark.java
  src/main/java/com/umc/tomorrow/domain/jobbookmark/exception/JobBookmarkException.java
  src/main/java/com/umc/tomorrow/domain/jobbookmark/exception/code/JobBookmarkErrorStatus.java
  src/main/java/com/umc/tomorrow/domain/jobbookmark/repository/JobBookmarkRepository.java
  src/main/java/com/umc/tomorrow/domain/jobbookmark/service/command/JobBookmarkCommandService.java
  src/main/java/com/umc/tomorrow/domain/jobbookmark/service/command/JobBookmarkCommandServiceImpl.java
  src/main/java/com/umc/tomorrow/domain/jobbookmark/service/query/JobBookmarkQueryService.java
  src/main/java/com/umc/tomorrow/domain/jobbookmark/service/query/JobBookmarkQueryServiceImpl.java
  src/main/java/com/umc/tomorrow/global/common/exception/code/GlobalErrorStatus.java
  src/main/resources/application.yml
Labels: enhancement

#144 Feat: 일자리 이미지 추가
  src/main/java/com/umc/tomorrow/domain/job/controller/command/JobCommandController.java
  src/main/java/com/umc/tomorrow/domain/job/converter/JobConverter.java
  src/main/java/com/umc/tomorrow/domain/job/dto/request/JobRequestDTO.java
  src/main/java/com/umc/tomorrow/global/common/exception/RestApiException.java
Labels: enhancement

#135 Feat: 1:N 채팅 구현
  build.gradle
  src/main/java/com/umc/tomorrow/domain/auth/security/CustomUserDetails.java
  src/main/java/com/umc/tomorrow/domain/auth/service/CustomUserDetailsService.java
  src/main/java/com/umc/tomorrow/domain/careertalk/controller/CareertalkController.java
  src/main/java/com/umc/tomorrow/domain/careertalk/dto/request/CreateCareertalkRequestDTO.java
  src/main/java/com/umc/tomorrow/domain/careertalk/dto/request/UpdateCareertalkRequestDTO.java
  src/main/java/com/umc/tomorrow/domain/careertalk/dto/response/GetCareertalkResponseDto.java
  src/main/java/com/umc/tomorrow/domain/careertalk/entity/Careertalk.java
  src/main/java/com/umc/tomorrow/domain/careertalk/service/command/CareertalkCommandService.java
  src/main/java/com/umc/tomorrow/domain/careertalk/service/command/CareertalkCommandServiceImpl.java
  src/main/java/com/umc/tomorrow/domain/careertalk/service/query/CareertalkQueryServiceImpl.java
  src/main/java/com/umc/tomorrow/domain/chatting/controller/ChatController.java
  src/main/java/com/umc/tomorrow/domain/chatting/converter/ChatConverter.java
  src/main/java/com/umc/tomorrow/domain/chatting/dto/request/CreateChatMessageRequestDTO.java
  src/main/java/com/umc/tomorrow/domain/chatting/dto/response/CreateChatMessageResponseDTO.java
  src/main/java/com/umc/tomorrow/domain/chatting/dto/response/GetChatMessageListResponseDTO.java
  src/main/java/com/umc/tomorrow/domain/chatting/dto/response/GetChatMessageResponseDTO.java
  src/main/java/com/umc/tomorrow/domain/chatting/entity/ChatPart.java
  src/main/java/com/umc/tomorrow/domain/chatting/entity/ChattingRoom.java
  src/main/java/com/umc/tomorrow/domain/chatting/entity/Message.java
  src/main/java/com/umc/tomorrow/domain/chatting/exception/ChatException.java
  src/main/java/com/umc/tomorrow/domain/chatting/exception/code/ChatErrorStatus.java
  src/main/java/com/umc/tomorrow/domain/chatting/repository/ChatPartRepository.java
  src/main/java/com/umc/tomorrow/domain/chatting/repository/ChattingRoomRepository.java
  src/main/java/com/umc/tomorrow/domain/chatting/repository/MessageRepository.java
  src/main/java/com/umc/tomorrow/domain/chatting/service/command/ChatBroadcastService.java
  src/main/java/com/umc/tomorrow/domain/chatting/service/command/ChatCommandService.java
  src/main/java/com/umc/tomorrow/domain/chatting/service/query/ChatQueryService.java
  src/main/java/com/umc/tomorrow/domain/resume/entity/Resume.java
  src/main/java/com/umc/tomorrow/global/config/AuthHandshakeInterceptor.java
  src/main/java/com/umc/tomorrow/global/config/AysncConfig.java
  src/main/java/com/umc/tomorrow/global/config/WebSocketConfig.java
  src/main/resources/static/test-chat.html
  src/main/resources/validation.properties
Labels: enhancement

#154 Feat: docker-compose.yml에 ngrinder 설정 추가
  docker/docker-compose.yml
Labels: enhancement

#138 Feat: 특정 일자리 공고 리뷰 목록 조회
  build.gradle
  src/main/java/com/umc/tomorrow/domain/career/service/query/CareerQueryServiceImpl.java
  src/main/java/com/umc/tomorrow/domain/introduction/exception/code/IntroductionStatus.java
  src/main/java/com/umc/tomorrow/domain/introduction/service/command/IntroductionCommandServiceImpl.java
  src/main/java/com/umc/tomorrow/domain/job/converter/JobConverter.java
  src/main/java/com/umc/tomorrow/domain/job/dto/response/JobDetailResponseDTO.java
  src/main/java/com/umc/tomorrow/domain/job/entity/BusinessVerification.java
  src/main/java/com/umc/tomorrow/domain/job/entity/Job.java
  src/main/java/com/umc/tomorrow/domain/job/entity/PersonalRegistration.java
  src/main/java/com/umc/tomorrow/domain/job/service/command/JobCommandServiceImpl.java
  src/main/java/com/umc/tomorrow/domain/review/controller/ReviewController.java
  src/main/java/com/umc/tomorrow/domain/review/dto/ReviewResponseDTO.java
  src/main/java/com/umc/tomorrow/domain/review/entity/Review.java
  src/main/java/com/umc/tomorrow/domain/review/repository/ReviewRepository.java
  src/main/java/com/umc/tomorrow/domain/review/service/ReviewService.java
  src/main/java/com/umc/tomorrow/domain/review/service/ReviewServiceImpl.java
  src/main/java/com/umc/tomorrow/domain/searchAndFilter/dto/request/JobSearchRequestDTO.java
Labels: enhancement

#176 Fix/swagger update/#175
  docker/Dockerfile
  src/main/java/com/umc/tomorrow/domain/careertalk/service/query/CareertalkQueryServiceImpl.java
  src/main/java/com/umc/tomorrow/global/infrastructure/s3/S3Uploader.java
Labels: bug

#177 Fix/swagger update/#175
  src/main/java/com/umc/tomorrow/domain/certificate/repository/CertificateRepository.java
  src/main/java/com/umc/tomorrow/domain/certificate/service/query/CertificateQueryServiceImpl.java
  src/main/java/com/umc/tomorrow/global/infrastructure/controller/S3Controller.java
Labels: bug

#170 Test: junit test구현
  src/main/java/com/umc/tomorrow/domain/introduction/controller/IntroductionCommandController.java
  src/main/java/com/umc/tomorrow/domain/introduction/service/IntroductionCommandService.java
  src/main/java/com/umc/tomorrow/domain/introduction/service/IntroductionCommandServiceImpl.java
  src/main/java/com/umc/tomorrow/domain/job/exception/code/JobErrorStatus.java
  src/main/java/com/umc/tomorrow/domain/job/service/command/JobCommandServiceImpl.java
  src/main/java/com/umc/tomorrow/domain/job/service/query/JobQueryServiceImpl.java
  src/main/java/com/umc/tomorrow/domain/member/entity/User.java
  src/main/java/com/umc/tomorrow/domain/review/entity/Review.java
  src/main/java/com/umc/tomorrow/domain/review/service/ReviewServiceImpl.java
  src/test/java/com/umc/tomorrow/domain/career/service/CareerServiceTest.java
  src/test/java/com/umc/tomorrow/domain/introduction/service/IntroductionServiceTest.java
  src/test/java/com/umc/tomorrow/domain/job/service/command/JobCommandServiceImplTest.java
  src/test/java/com/umc/tomorrow/domain/job/service/query/JobDetailServiceTest.java
  src/test/java/com/umc/tomorrow/domain/review/service/ReviewServiceImplTest.java
  src/test/java/com/umc/tomorrow/domain/searchAndFilter/service/query/JobSearchServiceImplTest.java
Labels: bug, enhancement
