Repository UMC-TOMORROW/Tomorrow-Backend, pull requests merged in 2025-07, with the labels that each got.

#4 Feat/security setting#1
  src/main/java/com/umc/tomorrow/global/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: enhancement

#9 Feat: JWT발급 및 구글 로그인 구현#8
  build.gradle
  docker/dokerFile
  src/main/java/com/umc/tomorrow/global/config/CorsMvcConfig.java
  src/main/java/com/umc/tomorrow/global/config/SecurityConfig.java
  src/main/java/com/umc/tomorrow/global/dto/CustomOAuth2User.java
  src/main/java/com/umc/tomorrow/global/dto/GoogleResponse.java
  src/main/java/com/umc/tomorrow/global/dto/NaverResponse.java
  src/main/java/com/umc/tomorrow/global/dto/OAuth2Response.java
  src/main/java/com/umc/tomorrow/global/dto/UserDTO.java
  src/main/java/com/umc/tomorrow/global/entity/UserEntity.java
  src/main/java/com/umc/tomorrow/global/jwt/JWTFilter.java
  src/main/java/com/umc/tomorrow/global/jwt/JWTUtil.java
  src/main/java/com/umc/tomorrow/global/oauth2/CustomSuccessHandler.java
  src/main/java/com/umc/tomorrow/global/repository/UserRepository.java
  src/main/java/com/umc/tomorrow/global/service/CustomOAuth2UserService.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: enhancement

#17 Feat/careertalk create and select#11
  src/main/java/com/umc/tomorrow/domain/careertalk/controller/CareertalkController.java
  src/main/java/com/umc/tomorrow/domain/careertalk/dto/request/CreateCareertalkRequestDto.java
  src/main/java/com/umc/tomorrow/domain/careertalk/dto/response/CreateCareertalkResponseDto.java
  src/main/java/com/umc/tomorrow/domain/careertalk/dto/response/GetCareertalkListResponseDto.java
  src/main/java/com/umc/tomorrow/domain/careertalk/dto/response/GetCareertalkResponseDto.java
  src/main/java/com/umc/tomorrow/domain/careertalk/entity/Careertalk.java
  src/main/java/com/umc/tomorrow/domain/careertalk/repository/CareertalkRepository.java
  src/main/java/com/umc/tomorrow/domain/careertalk/service/command/CareertalkCommandService.java
  src/main/java/com/umc/tomorrow/domain/careertalk/service/command/CareertalkCommandServiceImpl.java
  src/main/java/com/umc/tomorrow/domain/careertalk/service/query/CareertalkQueryService.java
  src/main/java/com/umc/tomorrow/domain/careertalk/service/query/CareertalkQueryServiceImpl.java
Labels: enhancement

#28 Feat/resume summary#26
  src/main/java/com/umc/tomorrow/domain/resume/controller/ResumeController.java
  src/main/java/com/umc/tomorrow/domain/resume/controller/ResumeSummaryController.java
  src/main/java/com/umc/tomorrow/domain/resume/converter/ResumeConverter.java
  src/main/java/com/umc/tomorrow/domain/resume/dto/request/ResumeSaveRequestDTO.java
  src/main/java/com/umc/tomorrow/domain/resume/dto/response/ResumeSummaryResponseDTO.java
  src/main/java/com/umc/tomorrow/domain/resume/entity/Certificate.java
  src/main/java/com/umc/tomorrow/domain/resume/entity/Experience.java
  src/main/java/com/umc/tomorrow/domain/resume/entity/Resume.java
  src/main/java/com/umc/tomorrow/domain/resume/repository/CertificateRepository.java
  src/main/java/com/umc/tomorrow/domain/resume/repository/ExperienceRepository.java
  src/main/java/com/umc/tomorrow/domain/resume/repository/ResumeRepository.java
  src/main/java/com/umc/tomorrow/domain/resume/service/ResumeService.java
  src/main/java/com/umc/tomorrow/domain/resume/service/ResumeSummaryService.java
Labels: enhancement

#32 Fix/EC2 setting을 위한 yml 파일 수정
  .gitignore
  src/main/resources/application-dev.yml
Labels: enhancement

#34 Fix/social login refactoring#33
  src/main/java/com/umc/tomorrow/domain/auth/security/CustomSuccessHandler.java
  src/main/java/com/umc/tomorrow/domain/careertalk/dto/response/GetCareertalkResponseDto.java
  src/main/java/com/umc/tomorrow/domain/careertalk/service/query/CareertalkQueryServiceImpl.java
  src/main/java/com/umc/tomorrow/domain/member/repository/UserRepository.java
  src/main/java/com/umc/tomorrow/global/common/base/BaseResponse.java
Labels: bug, enhancement

#40 Feat/회원 탈퇴, 회원 복구 api구현
  src/main/java/com/umc/tomorrow/domain/auth/security/CustomSuccessHandler.java
  src/main/java/com/umc/tomorrow/domain/member/controller/MemberController.java
  src/main/java/com/umc/tomorrow/domain/member/dto/UserConverter.java
  src/main/java/com/umc/tomorrow/domain/member/dto/request/DeactivateUserRequest.java
  src/main/java/com/umc/tomorrow/domain/member/dto/response/DeactivateUserResponse.java
  src/main/java/com/umc/tomorrow/domain/member/dto/response/RecoverUserResponse.java
  src/main/java/com/umc/tomorrow/domain/member/entity/User.java
  src/main/java/com/umc/tomorrow/domain/member/enums/Provider.java
  src/main/java/com/umc/tomorrow/domain/member/enums/UserStatus.java
  src/main/java/com/umc/tomorrow/domain/member/exception/MemberStatus.java
  src/main/java/com/umc/tomorrow/domain/member/repository/UserRepository.java
  src/main/java/com/umc/tomorrow/domain/member/service/MemberService.java
  src/main/resources/validation.properties
Labels: enhancement

#37 Feat/resume status#27
  src/main/java/com/umc/tomorrow/domain/application/controller/ApplicationController.java
  src/main/java/com/umc/tomorrow/domain/application/converter/ApplicationConverter.java
  src/main/java/com/umc/tomorrow/domain/application/dto/request/UpdateApplicationStatusRequestDTO.java
  src/main/java/com/umc/tomorrow/domain/application/dto/response/UpdateApplicationStatusResponseDTO.java
  src/main/java/com/umc/tomorrow/domain/application/entity/Application.java
  src/main/java/com/umc/tomorrow/domain/application/enums/ApplicationStatus.java
  src/main/java/com/umc/tomorrow/domain/application/exception/ApplicationErrorStatus.java
  src/main/java/com/umc/tomorrow/domain/application/exception/ApplicationException.java
  src/main/java/com/umc/tomorrow/domain/application/repository/ApplicationRepository.java
  src/main/java/com/umc/tomorrow/domain/application/service/command/ApplicationService.java
  src/main/java/com/umc/tomorrow/domain/job/entity/Job.java
  src/main/java/com/umc/tomorrow/domain/job/exception/JobErrorStatus.java
  src/main/java/com/umc/tomorrow/domain/member/entity/User.java
  src/main/java/com/umc/tomorrow/domain/resume/entity/Resume.java
  src/main/java/com/umc/tomorrow/global/common/base/BaseEntity.java
  src/main/java/com/umc/tomorrow/global/common/exception/code/GlobalErrorStatus.java
  src/main/resources/validation.properties
Labels: enhancement

#52 Feat/경력 - 조회 및 삭제 api구현
  src/main/java/com/umc/tomorrow/domain/career/controller/CareerCommandController.java
  src/main/java/com/umc/tomorrow/domain/career/converter/CareerConverter.java
  src/main/java/com/umc/tomorrow/domain/career/dto/request/CareerCreateRequestDTO.java
  src/main/java/com/umc/tomorrow/domain/career/dto/request/CareerUpdateRequestDTO.java
  src/main/java/com/umc/tomorrow/domain/career/dto/response/CareerCreateResponseDTO.java
  src/main/java/com/umc/tomorrow/domain/career/dto/response/CareerGetResponseDTO.java
  src/main/java/com/umc/tomorrow/domain/career/entity/Career.java
  src/main/java/com/umc/tomorrow/domain/career/enums/WorkPeriodType.java
  src/main/java/com/umc/tomorrow/domain/career/exception/CareerException.java
  src/main/java/com/umc/tomorrow/domain/career/exception/code/CareerStatus.java
  src/main/java/com/umc/tomorrow/domain/career/repository/CareerRepository.java
  src/main/java/com/umc/tomorrow/domain/career/service/conmmand/CareerCommandService.java
  src/main/java/com/umc/tomorrow/domain/career/service/conmmand/CareerCommandServiceImpl.java
  src/main/java/com/umc/tomorrow/domain/resume/converter/ResumeConverter.java
  src/main/java/com/umc/tomorrow/domain/resume/dto/request/ResumeSaveRequestDTO.java
  src/main/java/com/umc/tomorrow/domain/resume/dto/response/ResumeSummaryResponseDTO.java
  src/main/java/com/umc/tomorrow/domain/resume/entity/Experience.java
  src/main/java/com/umc/tomorrow/domain/resume/entity/Resume.java
  src/main/java/com/umc/tomorrow/domain/resume/repository/ExperienceRepository.java
  src/main/resources/validation.properties
Labels: enhancement

#55 Feat: docker, ci-cd 추가
  .github/workflows/ci-cd.yml
  docker/docker-compose.yml
  src/main/java/com/umc/tomorrow/domain/application/converter/ApplicationConverter.java
Labels: enhancement

#60 fix: 지원서 상세 조회 시 경험(Experience) 필드 관련 오류 수정
  src/main/java/com/umc/tomorrow/domain/application/converter/ApplicationConverter.java
  src/main/java/com/umc/tomorrow/domain/resume/entity/Experience.java
  src/main/java/com/umc/tomorrow/domain/resume/entity/Resume.java
Labels: bug

#64 feat: 지원자 조회 및 상태 변경 API 구현
  src/main/java/com/umc/tomorrow/domain/application/controller/ApplicationController.java
  src/main/java/com/umc/tomorrow/domain/application/converter/ApplicationConverter.java
  src/main/java/com/umc/tomorrow/domain/application/dto/response/ApplicantListResponseDTO.java
  src/main/java/com/umc/tomorrow/domain/application/repository/ApplicationRepository.java
  src/main/java/com/umc/tomorrow/domain/application/service/command/ApplicationService.java
  src/main/resources/application.yml
Labels: enhancement

#89 Chore/swagger and cors refactoring#88
  build.gradle
  src/main/java/com/umc/tomorrow/domain/Image/controller/S3Controller.java
  src/main/java/com/umc/tomorrow/domain/Image/s3/S3Uploader.java
  src/main/java/com/umc/tomorrow/domain/application/service/command/ApplicationService.java
  src/main/java/com/umc/tomorrow/global/config/AmazonConfig.java
  src/main/resources/application.yml
Labels: enhancement

#86 Fix: ci-cd 빌드 오류 수정
  src/main/java/com/umc/tomorrow/domain/application/service/command/ApplicationService.java
Labels: bug

#82 Feat: 공통 이메일 보내기 기능
  build.gradle
  docker/docker-compose.yml
  src/main/java/com/umc/tomorrow/domain/application/controller/command/ApplicationController.java
  src/main/java/com/umc/tomorrow/domain/application/service/command/ApplicationCommandService.java
  src/main/java/com/umc/tomorrow/domain/email/controller/EmailController.java
  src/main/java/com/umc/tomorrow/domain/email/dto/request/EmailRequestDTO.java
  src/main/java/com/umc/tomorrow/domain/email/dto/response/EmailResponseDTO.java
  src/main/java/com/umc/tomorrow/domain/email/enums/EmailContentProvider.java
  src/main/java/com/umc/tomorrow/domain/email/enums/EmailContentType.java
  src/main/java/com/umc/tomorrow/domain/email/enums/EmailType.java
  src/main/java/com/umc/tomorrow/domain/email/exception/EmailException.java
  src/main/java/com/umc/tomorrow/domain/email/exception/code/EmailErrorStatus.java
  src/main/java/com/umc/tomorrow/domain/email/service/EmailService.java
  src/main/resources/application.yml
  src/main/resources/validation.properties
Labels: enhancement

#99 Feat: 파일 업로드 및 삭제 기능
  src/main/java/com/umc/tomorrow/domain/application/converter/ApplicationConverter.java
  src/main/java/com/umc/tomorrow/domain/resume/certificate/controller/CertificateController.java
  src/main/java/com/umc/tomorrow/domain/resume/certificate/dto/response/CertificateResponse.java
  src/main/java/com/umc/tomorrow/domain/resume/certificate/entity/Certificate.java
  src/main/java/com/umc/tomorrow/domain/resume/certificate/exception/CertificateException.java
  src/main/java/com/umc/tomorrow/domain/resume/certificate/exception/code/CertificateErrorStatus.java
  src/main/java/com/umc/tomorrow/domain/resume/certificate/repository/CertificateRepository.java
  src/main/java/com/umc/tomorrow/domain/resume/certificate/service/command/CertificateCommandService.java
  src/main/java/com/umc/tomorrow/domain/resume/certificate/service/command/CertificateCommandServiceImpl.java
  src/main/java/com/umc/tomorrow/domain/resume/converter/ResumeConverter.java
  src/main/java/com/umc/tomorrow/domain/resume/entity/Resume.java
  src/main/java/com/umc/tomorrow/domain/resume/service/ResumeSummaryService.java
  src/main/java/com/umc/tomorrow/global/infrastructure/controller/S3Controller.java
  src/main/java/com/umc/tomorrow/global/infrastructure/s3/S3Uploader.java
  src/main/resources/application.yml
Labels: enhancement
